namespace: argo-rollouts
resources:
  - https://github.com/argoproj/argo-rollouts/releases/download/v1.6.6/install.yaml
  - https://github.com/argoproj/argo-rollouts/releases/download/v1.6.6/dashboard-install.yaml