apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
spec:
  destination:
    namespace: demo
    server: "https://kubernetes.default.svc"
  source:
    path: demo
    repoURL: "https://github.com/jorgelon/demo.git"
    targetRevision: main
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
