apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: job
spec:
  args:
    - name: service-name
  metrics:
    - name: job
      provider:
        job:
          spec:
            backoffLimit: 1
            template:
              spec:
                containers:
                  - name: test
                    image: my-image:latest
                    command:
                      [my-test-script, my-service.default.svc.cluster.local]
                restartPolicy: Never
